CREATE TABLE PPZOS_AGG AS
SELECT AVG(PPZOS.CAPACITY) AS KAPACITA
, CAST(AVG(PPZOS.PRICE) AS INT) AS PRUMERNA_CENA
, PPZOS.CHANNEL
, PPZOS.PARKING_ZONE
, PPZOS.DATUM
, AVG(PPZOS.OBYVATELE) AS POCET_OBYVATEL
, AVG(PPZOS.PRECIPITATION) AS SRAZKY
, AVG(PPZOS.TEMPERATURE) AS TEPLOTA
, PPZOS.DISTRICT
, CAST(COUNT(TRANSACTION_ID) AS INT) AS POCET_TRANSAKCI
, CAST((PRUMERNA_CENA / POCET_TRANSAKCI) AS FLOAT) AS PRUMER_ZA_TRANSAKCI

FROM PPZOS
GROUP BY PPZOS.DATUM, PPZOS.PARKING_ZONE, PPZOS.CHANNEL, PPZOS.DISTRICT
ORDER BY PPZOS.PARKING_ZONE, PPZOS.DATUM;