CREATE OR REPLACE TABLE PPZO AS
SELECT  A.VALIDITY_FROM
, A.VALIDITY_TO	
, A.DATUM_CAS
, A.PARKING_ZONE
, A.TICKET_BOUGHT
, A.DATUM
, A.PRICE
, A.CHANNEL
, A.TRANSACTION_ID
, B.TEMPERATURE
, B.PRECIPITATION
, C."district" AS DISTRICT
, C."lng" AS LNG
, C."lat" as LAT
, C."type" AS TYPE
, C."capacity" AS CAPACITY
, REPLACE(D.POCET_OB, ' ', '') AS OBYVATELE
FROM PARKOMATY_SPOJ_DATUM as A
LEFT JOIN POCASI as B
ON A.DATUM = B.DATUM
INNER JOIN "Parking_zones" AS C
ON A.PARKING_ZONE =C."id" 
LEFT JOIN "pocet-obyvatel-district" AS D
ON D.DISTRICT = C."district";